### ISSUE TITLE
empty repository?

### ISSUE THREAD

**Issue by XiaoLiuAI** [RingBDStack/MISMV#1]
Hello

I read your works published on KDD and I am very interested in the innovative idea presented in the paper. But this repository is completely empty, hence I could not reproduce your work. Would you still plan to publish your code?

**Comment by YuweiCao-UIC** [comment]
> Hello
> 
> I read your works published on KDD and I am very interested in the innovative idea presented in the paper. But this repository is completely empty, hence I could not reproduce your work. Would you still plan to publish your code?

Thank you for showing interests. The code has been uploaded. We also made all data publicly accessible. Please find our pro-processed datasets, constructed HINs and learned embeddings at:
[https://drive.google.com/drive/folders/12hvgM7IhV10ezJAOpWzvbczXB219ThUq?usp=sharing]()

**Comment by XiaoLiuAI** [comment]
Thank you very much!
